### ISSUE TITLE
Failing to load default config: builtins.applications.actions expects a map

### ISSUE THREAD

**Issue by TomFaulkner** [abenz1267/walker#195]
**Describe the bug**
Failing to load default config: builtins.applications.actions expects a map. The default config has builtins.applications.actions: true. However, the application is expecting a map.

Replacing true with `{}` allows walker to start.

**Version**
0.11.2

**Minimal Config**
Delete config.json, start again

**To Reproduce**
Delete config.json, start again

**Expected behavior**
Start as normal

**Screenshots**
![image](https://github.com/user-attachments/assets/fbd5f3b6-74d5-4040-8a7c-846ac20ac1f0)

**Desktop**
Arch on Hyprland 0.46.2

**Additional context**
Unknown earlier version was working. Last change to config was on September 25th. My existing config has `true` for this field, so it seems behavior was changed rather than the default config.

**Comment by abenz1267** [comment]
https://github.com/abenz1267/walker/blob/master/internal%2Fconfig%2Fconfig.default.json

That's the current default config. As you can see the relevant value is not a boolean...it hasn't been for quite some versions now.

I'm pretty sure the cause is your system. Have you built walker from source at some point? Install via package manager.

The default config is correct.

**Comment by TomFaulkner** [comment]
I installed using a package manager. I don't believe I've ever built it from source.

I think when I killed it I didn't actually kill the process and then it replaced the config file with the in memory config on the next execution.

Anyway, after checking that it was indeed killed, the newly generated config is works.

Thanks for following up, merry Christmas!
