### ISSUE TITLE
Desktop entries are missing if they have actions

### ISSUE THREAD

**Issue by flytaly** [abenz1267/walker#51]
Example:
```ini
[Desktop Entry]
Name=Telegram Desktop
Actions=quit;
....
[Desktop Action quit]
Name=Quit Telegram
...
```
The main "Telegram Desktop" entry is missing.

![image](https://github.com/user-attachments/assets/9d5424c4-6a53-42d2-bd59-9bcb8ae34c1c)

**Comment by abenz1267** [comment]
Yeah, cuz otherwise you'll get duplicate entries for apps. F.e. Firefox would give you 2 results to simply open it.

I'd like a solution that avoids that. 

Tbh the telegram desktop file seems to be an outlier here, or not? I never encountered this issue with other apps. But it's not out of spec to NOT include the default entry as an action. So the file isn't broken in that sense.

**Comment by abenz1267** [comment]
fixed.
